version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: erp_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - erp-network

  web:
    image: nginx:alpine
    container_name: erp_web
    ports:
      - "8183:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - erp-network

  db:
    image: mysql:8.0
    container_name: erp_db
    restart: always
    environment:
      MYSQL_DATABASE: erp
      MYSQL_USER: erpuser
      MYSQL_PASSWORD: erp123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - erp-network

networks:
  erp-network:
    driver: bridge

volumes:
  db_data:
